// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AgentSession struct {
	ID              string       `json:"id"`
	AgentType       string       `json:"agent_type"`
	NativeSessionID string       `json:"native_session_id"`
	Title           string       `json:"title"`
	Status          string       `json:"status"`
	NormalizedPath  string       `json:"normalized_path"`
	SizeBytes       int64        `json:"size_bytes"`
	StartedAt       sql.NullTime `json:"started_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	AdapterVersion  int64        `json:"adapter_version"`
}

type AgentSessionLaunch struct {
	ID        string       `json:"id"`
	SandboxID string       `json:"sandbox_id"`
	AgentType string       `json:"agent_type"`
	StartedAt time.Time    `json:"started_at"`
	EndedAt   sql.NullTime `json:"ended_at"`
}

type AgentSessionSource struct {
	SessionID   string    `json:"session_id"`
	SandboxID   string    `json:"sandbox_id"`
	SandboxName string    `json:"sandbox_name"`
	NativePath  string    `json:"native_path"`
	RawPath     string    `json:"raw_path"`
	SizeBytes   int64     `json:"size_bytes"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Sandbox struct {
	ID                    string         `json:"id"`
	ContainerID           sql.NullString `json:"container_id"`
	HostOriginDir         string         `json:"host_origin_dir"`
	SandboxWorkDir        string         `json:"sandbox_work_dir"`
	ImageName             string         `json:"image_name"`
	DnsDomain             sql.NullString `json:"dns_domain"`
	EnvFile               sql.NullString `json:"env_file"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	AgentType             sql.NullString `json:"agent_type"`
	OriginalGitOrigin     sql.NullString `json:"original_git_origin"`
	OriginalGitBranch     sql.NullString `json:"original_git_branch"`
	OriginalGitCommit     sql.NullString `json:"original_git_commit"`
	OriginalGitIsDirty    bool           `json:"original_git_is_dirty"`
	AllowedDomains        sql.NullString `json:"allowed_domains"`
	Cpu                   sql.NullInt64  `json:"cpu"`
	MemoryMb              sql.NullInt64  `json:"memory_mb"`
	DefaultUsername       sql.NullString `json:"default_username"`
	DefaultUid            sql.NullString `json:"default_uid"`
	Name                  string         `json:"name"`
	State                 string         `json:"state"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
	TrashWorkDir          sql.NullString `json:"trash_work_dir"`
	ProfileName           sql.NullString `json:"profile_name"`
	MountSpecs            sql.NullString `json:"mount_specs"`
	ContainerBootstrapped bool           `json:"container_bootstrapped"`
	SessionArchiveEnabled bool           `json:"session_archive_enabled"`
	HostPorts             sql.NullString `json:"host_ports"`
}
