// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Sandbox struct {
	ID                 string         `json:"id"`
	ContainerID        sql.NullString `json:"container_id"`
	HostOriginDir      string         `json:"host_origin_dir"`
	SandboxWorkDir     string         `json:"sandbox_work_dir"`
	ImageName          string         `json:"image_name"`
	DnsDomain          sql.NullString `json:"dns_domain"`
	EnvFile            sql.NullString `json:"env_file"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	AgentType          sql.NullString `json:"agent_type"`
	OriginalGitOrigin  sql.NullString `json:"original_git_origin"`
	OriginalGitBranch  sql.NullString `json:"original_git_branch"`
	OriginalGitCommit  sql.NullString `json:"original_git_commit"`
	OriginalGitIsDirty bool           `json:"original_git_is_dirty"`
	AllowedDomains     sql.NullString `json:"allowed_domains"`
	Cpu                sql.NullInt64  `json:"cpu"`
	MemoryMb           sql.NullInt64  `json:"memory_mb"`
	DefaultUsername    sql.NullString `json:"default_username"`
	DefaultUid         sql.NullString `json:"default_uid"`
	Name               string         `json:"name"`
	State              string         `json:"state"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	TrashWorkDir       sql.NullString `json:"trash_work_dir"`
	ProfileName        sql.NullString `json:"profile_name"`
	MountSpecs         sql.NullString `json:"mount_specs"`
	HostPorts          sql.NullString `json:"host_ports"`
}
