// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes
WHERE id = ?
`

func (q *Queries) DeleteSandbox(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSandbox, id)
	return err
}

const getActiveSandboxByName = `-- name: GetActiveSandboxByName :one
SELECT id, container_id, host_origin_dir, sandbox_work_dir, image_name, dns_domain, env_file, created_at, updated_at, agent_type, original_git_origin, original_git_branch, original_git_commit, original_git_is_dirty, allowed_domains, cpu, memory_mb, default_username, default_uid, name, state, deleted_at, trash_work_dir, profile_name, mount_specs, host_ports FROM sandboxes
WHERE name = ? AND state = 'active'
LIMIT 1
`

func (q *Queries) GetActiveSandboxByName(ctx context.Context, name string) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, getActiveSandboxByName, name)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.HostOriginDir,
		&i.SandboxWorkDir,
		&i.ImageName,
		&i.DnsDomain,
		&i.EnvFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentType,
		&i.OriginalGitOrigin,
		&i.OriginalGitBranch,
		&i.OriginalGitCommit,
		&i.OriginalGitIsDirty,
		&i.AllowedDomains,
		&i.Cpu,
		&i.MemoryMb,
		&i.DefaultUsername,
		&i.DefaultUid,
		&i.Name,
		&i.State,
		&i.DeletedAt,
		&i.TrashWorkDir,
		&i.ProfileName,
		&i.MountSpecs,
		&i.HostPorts,
	)
	return i, err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, container_id, host_origin_dir, sandbox_work_dir, image_name, dns_domain, env_file, created_at, updated_at, agent_type, original_git_origin, original_git_branch, original_git_commit, original_git_is_dirty, allowed_domains, cpu, memory_mb, default_username, default_uid, name, state, deleted_at, trash_work_dir, profile_name, mount_specs, host_ports FROM sandboxes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id string) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.HostOriginDir,
		&i.SandboxWorkDir,
		&i.ImageName,
		&i.DnsDomain,
		&i.EnvFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentType,
		&i.OriginalGitOrigin,
		&i.OriginalGitBranch,
		&i.OriginalGitCommit,
		&i.OriginalGitIsDirty,
		&i.AllowedDomains,
		&i.Cpu,
		&i.MemoryMb,
		&i.DefaultUsername,
		&i.DefaultUid,
		&i.Name,
		&i.State,
		&i.DeletedAt,
		&i.TrashWorkDir,
		&i.ProfileName,
		&i.MountSpecs,
		&i.HostPorts,
	)
	return i, err
}

const getSandboxesByImage = `-- name: GetSandboxesByImage :many
SELECT id, container_id, host_origin_dir, sandbox_work_dir, image_name, dns_domain, env_file, created_at, updated_at, agent_type, original_git_origin, original_git_branch, original_git_commit, original_git_is_dirty, allowed_domains, cpu, memory_mb, default_username, default_uid, name, state, deleted_at, trash_work_dir, profile_name, mount_specs, host_ports FROM sandboxes
WHERE image_name = ? AND state = 'active'
ORDER BY created_at DESC
`

func (q *Queries) GetSandboxesByImage(ctx context.Context, imageName string) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, getSandboxesByImage, imageName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.HostOriginDir,
			&i.SandboxWorkDir,
			&i.ImageName,
			&i.DnsDomain,
			&i.EnvFile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentType,
			&i.OriginalGitOrigin,
			&i.OriginalGitBranch,
			&i.OriginalGitCommit,
			&i.OriginalGitIsDirty,
			&i.AllowedDomains,
			&i.Cpu,
			&i.MemoryMb,
			&i.DefaultUsername,
			&i.DefaultUid,
			&i.Name,
			&i.State,
			&i.DeletedAt,
			&i.TrashWorkDir,
			&i.ProfileName,
			&i.MountSpecs,
			&i.HostPorts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedSandboxes = `-- name: ListDeletedSandboxes :many
SELECT id, container_id, host_origin_dir, sandbox_work_dir, image_name, dns_domain, env_file, created_at, updated_at, agent_type, original_git_origin, original_git_branch, original_git_commit, original_git_is_dirty, allowed_domains, cpu, memory_mb, default_username, default_uid, name, state, deleted_at, trash_work_dir, profile_name, mount_specs, host_ports FROM sandboxes
WHERE state = 'deleted'
ORDER BY deleted_at DESC, created_at DESC
`

func (q *Queries) ListDeletedSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.HostOriginDir,
			&i.SandboxWorkDir,
			&i.ImageName,
			&i.DnsDomain,
			&i.EnvFile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentType,
			&i.OriginalGitOrigin,
			&i.OriginalGitBranch,
			&i.OriginalGitCommit,
			&i.OriginalGitIsDirty,
			&i.AllowedDomains,
			&i.Cpu,
			&i.MemoryMb,
			&i.DefaultUsername,
			&i.DefaultUid,
			&i.Name,
			&i.State,
			&i.DeletedAt,
			&i.TrashWorkDir,
			&i.ProfileName,
			&i.MountSpecs,
			&i.HostPorts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxes = `-- name: ListSandboxes :many
SELECT id, container_id, host_origin_dir, sandbox_work_dir, image_name, dns_domain, env_file, created_at, updated_at, agent_type, original_git_origin, original_git_branch, original_git_commit, original_git_is_dirty, allowed_domains, cpu, memory_mb, default_username, default_uid, name, state, deleted_at, trash_work_dir, profile_name, mount_specs, host_ports FROM sandboxes
WHERE state = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.HostOriginDir,
			&i.SandboxWorkDir,
			&i.ImageName,
			&i.DnsDomain,
			&i.EnvFile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentType,
			&i.OriginalGitOrigin,
			&i.OriginalGitBranch,
			&i.OriginalGitCommit,
			&i.OriginalGitIsDirty,
			&i.AllowedDomains,
			&i.Cpu,
			&i.MemoryMb,
			&i.DefaultUsername,
			&i.DefaultUid,
			&i.Name,
			&i.State,
			&i.DeletedAt,
			&i.TrashWorkDir,
			&i.ProfileName,
			&i.MountSpecs,
			&i.HostPorts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSandbox = `-- name: RenameSandbox :exec
UPDATE sandboxes
SET name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND state = 'active'
`

type RenameSandboxParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenameSandbox(ctx context.Context, arg RenameSandboxParams) error {
	_, err := q.db.ExecContext(ctx, renameSandbox, arg.Name, arg.ID)
	return err
}

const softDeleteSandbox = `-- name: SoftDeleteSandbox :exec
UPDATE sandboxes
SET state = 'deleted',
    container_id = NULL,
    deleted_at = CURRENT_TIMESTAMP,
    trash_work_dir = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SoftDeleteSandboxParams struct {
	TrashWorkDir sql.NullString `json:"trash_work_dir"`
	ID           string         `json:"id"`
}

func (q *Queries) SoftDeleteSandbox(ctx context.Context, arg SoftDeleteSandboxParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSandbox, arg.TrashWorkDir, arg.ID)
	return err
}

const updateContainerID = `-- name: UpdateContainerID :exec
UPDATE sandboxes
SET container_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateContainerIDParams struct {
	ContainerID sql.NullString `json:"container_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateContainerID(ctx context.Context, arg UpdateContainerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateContainerID, arg.ContainerID, arg.ID)
	return err
}

const upsertSandbox = `-- name: UpsertSandbox :exec
INSERT INTO sandboxes (
    id, name, state, container_id, host_origin_dir, sandbox_work_dir,
    image_name, dns_domain, env_file, agent_type, profile_name,
    original_git_origin, original_git_branch, original_git_commit,
    original_git_is_dirty, allowed_domains, host_ports, mount_specs,
    cpu, memory_mb, default_username, default_uid,
    deleted_at, trash_work_dir
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    state = excluded.state,
    container_id = excluded.container_id,
    host_origin_dir = excluded.host_origin_dir,
    sandbox_work_dir = excluded.sandbox_work_dir,
    image_name = excluded.image_name,
    dns_domain = excluded.dns_domain,
    env_file = excluded.env_file,
    agent_type = excluded.agent_type,
    profile_name = excluded.profile_name,
    updated_at = CURRENT_TIMESTAMP,
    original_git_origin = excluded.original_git_origin,
    original_git_branch = excluded.original_git_branch,
    original_git_commit = excluded.original_git_commit,
    original_git_is_dirty = excluded.original_git_is_dirty,
    allowed_domains = excluded.allowed_domains,
    host_ports = excluded.host_ports,
    mount_specs = excluded.mount_specs,
    cpu = excluded.cpu,
    memory_mb = excluded.memory_mb,
    default_username = excluded.default_username,
    default_uid = excluded.default_uid,
    deleted_at = excluded.deleted_at,
    trash_work_dir = excluded.trash_work_dir
`

type UpsertSandboxParams struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	State              string         `json:"state"`
	ContainerID        sql.NullString `json:"container_id"`
	HostOriginDir      string         `json:"host_origin_dir"`
	SandboxWorkDir     string         `json:"sandbox_work_dir"`
	ImageName          string         `json:"image_name"`
	DnsDomain          sql.NullString `json:"dns_domain"`
	EnvFile            sql.NullString `json:"env_file"`
	AgentType          sql.NullString `json:"agent_type"`
	ProfileName        sql.NullString `json:"profile_name"`
	OriginalGitOrigin  sql.NullString `json:"original_git_origin"`
	OriginalGitBranch  sql.NullString `json:"original_git_branch"`
	OriginalGitCommit  sql.NullString `json:"original_git_commit"`
	OriginalGitIsDirty bool           `json:"original_git_is_dirty"`
	AllowedDomains     sql.NullString `json:"allowed_domains"`
	HostPorts          sql.NullString `json:"host_ports"`
	MountSpecs         sql.NullString `json:"mount_specs"`
	Cpu                sql.NullInt64  `json:"cpu"`
	MemoryMb           sql.NullInt64  `json:"memory_mb"`
	DefaultUsername    sql.NullString `json:"default_username"`
	DefaultUid         sql.NullString `json:"default_uid"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	TrashWorkDir       sql.NullString `json:"trash_work_dir"`
}

func (q *Queries) UpsertSandbox(ctx context.Context, arg UpsertSandboxParams) error {
	_, err := q.db.ExecContext(ctx, upsertSandbox,
		arg.ID,
		arg.Name,
		arg.State,
		arg.ContainerID,
		arg.HostOriginDir,
		arg.SandboxWorkDir,
		arg.ImageName,
		arg.DnsDomain,
		arg.EnvFile,
		arg.AgentType,
		arg.ProfileName,
		arg.OriginalGitOrigin,
		arg.OriginalGitBranch,
		arg.OriginalGitCommit,
		arg.OriginalGitIsDirty,
		arg.AllowedDomains,
		arg.HostPorts,
		arg.MountSpecs,
		arg.Cpu,
		arg.MemoryMb,
		arg.DefaultUsername,
		arg.DefaultUid,
		arg.DeletedAt,
		arg.TrashWorkDir,
	)
	return err
}
