-- Code generated by go generate; DO NOT EDIT.
-- Source of truth: internal/db/migrations/*.up.sql.

CREATE TABLE agent_session_launches (
    id TEXT PRIMARY KEY,
    sandbox_id TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at DATETIME
);

CREATE TABLE agent_session_sources (
    session_id TEXT NOT NULL,
    sandbox_id TEXT NOT NULL,
    sandbox_name TEXT NOT NULL,
    native_path TEXT NOT NULL,
    raw_path TEXT PRIMARY KEY,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE agent_sessions (
    id TEXT PRIMARY KEY,
    agent_type TEXT NOT NULL,
    native_session_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'raw-only',
    normalized_path TEXT NOT NULL DEFAULT '',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    started_at DATETIME,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adapter_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE sandboxes (
    id TEXT PRIMARY KEY,
    container_id TEXT,
    host_origin_dir TEXT NOT NULL,
    sandbox_work_dir TEXT NOT NULL,
    image_name TEXT NOT NULL,
    dns_domain TEXT,
    env_file TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    agent_type TEXT DEFAULT 'default',
    original_git_origin TEXT,
    original_git_branch TEXT,
    original_git_commit TEXT,
    original_git_is_dirty BOOLEAN NOT NULL DEFAULT 0,
    allowed_domains TEXT,
    cpu INT,
    memory_mb INT,
    default_username TEXT,
    default_uid TEXT,
    name TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT 'active',
    deleted_at DATETIME,
    trash_work_dir TEXT,
    profile_name TEXT,
    mount_specs TEXT,
    container_bootstrapped BOOLEAN NOT NULL DEFAULT 1,
    session_archive_enabled BOOLEAN NOT NULL DEFAULT 0,
    host_ports TEXT
);

CREATE UNIQUE INDEX idx_active_sandbox_name ON sandboxes(name) WHERE state = 'active';

CREATE INDEX idx_agent_session_launches_active ON agent_session_launches(sandbox_id, ended_at);

CREATE INDEX idx_agent_session_sources_sandbox_id ON agent_session_sources(sandbox_id);

CREATE INDEX idx_agent_sessions_updated_at ON agent_sessions(updated_at DESC);

CREATE INDEX idx_container_id ON sandboxes(container_id);

CREATE INDEX idx_sandboxes_state ON sandboxes(state);
